# Generated by Django 3.2 on 2021-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('slot', models.CharField(default='morning', max_length=100)),
                ('cardio', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
